apiVersion: v1
kind: Service
metadata:
  name: three-tier-api
  namespace: infra-lab
  labels:
    app: three-tier-api
spec:
  type: ClusterIP
  selector:
    app: three-tier-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: three-tier-api
  namespace: infra-lab
spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: three-tier-api
  template:
    metadata:
      labels:
        app: three-tier-api
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api
          image: localhost/three-tier-api:pr2
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: PGHOST
              value: postgres
            - name: PGDATABASE
              value: labdb
            - name: PGUSER
              value: labuser
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-auth
                  key: password
            - name: TMPDIR
              value: /tmp
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: temp
              mountPath: /tmp
          startupProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 3
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            periodSeconds: 5
            timeoutSeconds: 3
      volumes:
        - name: temp
          emptyDir:
            sizeLimit: 64Mi
