---
- name: Reload SSH
  ansible.builtin.systemd_service:
    name: ssh
    state: reloaded

- name: Restart auditd
  ansible.builtin.command:
    argv: [/usr/sbin/service, auditd, restart]
  changed_when: true

- name: Load audit rules
  ansible.builtin.command:
    argv: [/sbin/augenrules, --load]
  changed_when: true
