variable "aws_region" {
  type        = string
  description = "AWS region for the disposable lab."
  default     = "us-east-1"
}

variable "run_id" {
  type        = string
  description = "Unique identifier for this temporary deployment."
  validation {
    condition     = can(regex("^[a-z0-9-]{6,32}$", var.run_id))
    error_message = "run_id must contain 6-32 lowercase letters, digits, or hyphens."
  }
}

variable "expires_at" {
  type        = string
  description = "UTC timestamp for finding stale lab resources; informational tag, not automated deletion."
}

variable "allowed_cidr" {
  type        = string
  description = "Your workstation's public IPv4 /32 for SSH and demo HTTP access."
  validation {
    condition     = can(cidrhost(var.allowed_cidr, 0)) && endswith(var.allowed_cidr, "/32")
    error_message = "allowed_cidr must be an IPv4 /32."
  }
}

variable "ssh_public_key" {
  type        = string
  description = "Ephemeral workstation SSH public key (generated by the runner)."
  sensitive   = true
}

variable "instance_type" {
  type        = string
  default     = "t3.small"
  description = "EC2 instance type for all three roles; override with TF_VAR_instance_type."
}
