"""Parameterized PostgreSQL operations; no per-Pod incident state or schema creation."""

import os
from contextlib import closing
from uuid import uuid4

import psycopg2
from psycopg2.extras import RealDictCursor

FIELDS = "id, title, description, severity, status, source, notes, created_at, updated_at"


def _connect():
    return psycopg2.connect(
        host=os.environ["PGHOST"],
        dbname=os.getenv("PGDATABASE", "labdb"),
        user=os.getenv("PGUSER", "labuser"),
        password=os.environ["PGPASSWORD"],
        connect_timeout=3,
    )


def _record(row):
    if row is None:
        return None
    result = dict(row)
    result["id"] = str(result["id"])
    for field in ("created_at", "updated_at"):
        result[field] = result[field].isoformat()
    return result


def create_incident(title, description, severity):
    # The incident UUID is generated by the API, not tied to any Flask worker.
    with closing(_connect()) as connection:
        with connection:
            with connection.cursor(cursor_factory=RealDictCursor) as cursor:
                cursor.execute(
                    "INSERT INTO incidents (id, title, description, severity) "
                    "VALUES (%s::uuid, %s, %s, %s) RETURNING " + FIELDS,
                    (str(uuid4()), title, description, severity),
                )
                return _record(cursor.fetchone())


def list_incidents(limit):
    with closing(_connect()) as connection:
        with connection:
            with connection.cursor(cursor_factory=RealDictCursor) as cursor:
                cursor.execute(
                    "SELECT " + FIELDS
                    + " FROM incidents ORDER BY created_at DESC, id DESC LIMIT %s",
                    (limit,),
                )
                return [_record(row) for row in cursor.fetchall()]


def get_incident(incident_id):
    with closing(_connect()) as connection:
        with connection:
            with connection.cursor(cursor_factory=RealDictCursor) as cursor:
                cursor.execute(
                    "SELECT " + FIELDS + " FROM incidents WHERE id = %s::uuid",
                    (incident_id,),
                )
                return _record(cursor.fetchone())


def update_incident(incident_id, status, notes):
    with closing(_connect()) as connection:
        with connection:
            with connection.cursor(cursor_factory=RealDictCursor) as cursor:
                cursor.execute(
                    "UPDATE incidents SET status = COALESCE(%s, status), "
                    "notes = COALESCE(%s, notes), updated_at = NOW() "
                    "WHERE id = %s::uuid RETURNING " + FIELDS,
                    (status, notes, incident_id),
                )
                return _record(cursor.fetchone())
